### ISSUE TITLE
Element Templates CLI Does Not Apply Properties as Expected

### ISSUE THREAD

**Issue by Oleksiivanov** [bpmn-io/element-templates-cli#15]
### Describe the Bug

The element-templates-cli does not apply specified properties from a JSON template to the BPMN model correctly, affecting the configuration of service tasks for DynamoDB operations.

### Steps to Reproduce

1. Open[ the element-templates-cli](https://github.com/bpmn-io/element-templates-cli) and configure it with the provided JSON template and bpmn files : 
 - add `add-item.bpmn` to `test/fixtures/diagrams`
<details>
  <summary>add-item.bpmn click to expand!</summary>

  ```bpmn
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_1c27vni" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.16.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.3.0">
  <bpmn:process id="Process_0hqfcqr1" isExecutable="true">
    <bpmn:task id="ServiceTask" />
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_0hqfcqr1">
      <bpmndi:BPMNShape id="Activity_di" bpmnElement="ServiceTask">
        <dc:Bounds x="160" y="80" width="100" height="80" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>

```
</details>

 - add `add-item_expected.bpmn` to `test/fixtures/diagrams`
 <details>
  <summary>add-item_expected.bpmn click to expand!</summary>

  ```bpmn
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:zeebe="http://camunda.org/schema/zeebe/1.0" xmlns:modeler="http://camunda.org/schema/modeler/1.0" id="Definitions_1c27vni" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="5.16.0" modeler:executionPlatform="Camunda Cloud" modeler:executionPlatformVersion="8.3.0">
  <bpmn:process id="Process_0hqfcqr1" isExecutable="true">
    <bpmn:serviceTask id="ServiceTask" zeebe:modelerTemplate="05d1c06a-b65d-428c-8ca0-10c14b3fb0ee" zeebe:modelerTemplateVersion="3">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="io.camunda:aws-dynamodb:1" />
        <zeebe:ioMapping>
          <zeebe:input source="itemOperation" target="input.operationGroup" />
          <zeebe:input source="addItem" target="input.itemOperation" />
          <zeebe:input source="tableName" target="input.tableName" />
          <zeebe:input source="={&#34;id&#34;:&#34;value&#34;}" target="input.item" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
      <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_0hqfcqr1">
          <bpmndi:BPMNShape id="Activity_1rrhra2_di" bpmnElement="ServiceTask">
              <dc:Bounds x="160" y="80" width="100" height="80" />
          </bpmndi:BPMNShape>
      </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</bpmn:definitions>

```
</details>

 - add [add-item.json](https://github.com/bpmn-io/element-templates-cli/files/14193088/add-item.json)
 to `test/fixtures/templates/`
 - add new `add-item` test to cliSpec.js : 
 
<img width="620" alt="Screenshot 2024-02-07 at 13 24 05" src="https://github.com/bpmn-io/element-templates-cli/assets/108869886/6638b445-5ab6-4fb1-9523-6f5b4d1ecddd">

2. run all tests : `npm run build && npm run test`

Observe that properties related to DynamoDB operations, such as tableName and item, are not applied as expected. : 
<img width="1174" alt="Screenshot 2024-02-07 at 13 27 29" src="https://github.com/bpmn-io/element-templates-cli/assets/108869886/2fa11d66-185f-4349-8a69-f41a23b0cc43">

### Expected Behavior

The BPMN model generated by the element-templates-cli should correctly include all specified properties from the JSON template. This includes inputs for tableName and item, allowing for proper interaction with DynamoDB within the process.

### Environment

- OS: MacOS
- Library version: [v0.2.2](https://github.com/bpmn-io/element-templates-cli/releases/tag/v0.2.2)

----

Depends on https://github.com/camunda/camunda-modeler/issues/4124

**Comment by barmac** [comment]
Thanks for reporting. I'll check if I can reproduce it, and come back with results.

**Comment by barmac** [comment]
Hey, I tried this out in the current Desktop Modeler nightly build, and the result was:

```xml
  <bpmn:process id="Process_0mc4oc6" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" />
    <bpmn:serviceTask id="Activity_1tnooja" zeebe:modelerTemplate="05d1c06a-b65d-428c-8ca0-10c14b3fb0ee" zeebe:modelerTemplateVersion="3">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="io.camunda:aws-dynamodb:1" />
        <zeebe:ioMapping>
          <zeebe:input source="itemOperation" target="input.operationGroup" />
          <zeebe:input source="addItem" target="input.itemOperation" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
```

So it's what this tool generates.

**Comment by barmac** [comment]
5.19.0

```xml
  <bpmn:process id="Process_1pi1tsj" isExecutable="true">
    <bpmn:startEvent id="StartEvent_1" />
    <bpmn:serviceTask id="Activity_03hp3ck" zeebe:modelerTemplate="05d1c06a-b65d-428c-8ca0-10c14b3fb0ee" zeebe:modelerTemplateVersion="3">
      <bpmn:extensionElements>
        <zeebe:taskDefinition type="io.camunda:aws-dynamodb:1" />
        <zeebe:ioMapping>
          <zeebe:input source="itemOperation" target="input.operationGroup" />
          <zeebe:input source="addItem" target="input.itemOperation" />
        </zeebe:ioMapping>
      </bpmn:extensionElements>
    </bpmn:serviceTask>
  </bpmn:process>
```

but on 5.17.0 I can reproduce what you pasted.

**Comment by barmac** [comment]
So this is broken from 5.18.0 on.

**Comment by barmac** [comment]
Between the versions 5.17.0 and 5.18.0, we updated the templates project:

```diff
-    "bpmn-js-element-templates": "^1.7.0",
+    "bpmn-js-element-templates": "^1.8.0",
```

**Comment by barmac** [comment]
Only a single feature was shipped, and it didn't change the production code apart from a comment: https://github.com/bpmn-io/bpmn-js-element-templates/pull/30/files#diff-f8200a0ea8c31c5996490cbd7c2337350b21eea60f66122f98f28dcd37e5838d

**Comment by barmac** [comment]
❯ git diff v1.7.0 v1.8.0 -- src
diff --git a/src/cloud-element-templates/util/propertyUtil.js b/src/cloud-element-templates/util/propertyUtil.js
index 267c087..985a7f8 100644
--- a/src/cloud-element-templates/util/propertyUtil.js
+++ b/src/cloud-element-templates/util/propertyUtil.js
@@ -772,7 +772,7 @@ export function unsetProperty(commandStack, element, property) {
     });
   }

-  // bpmn:Message#property
+  // bpmn:Message#zeebe:subscription#property
   if (type === MESSAGE_ZEEBE_SUBSCRIPTION_PROPERTY_TYPE) {
     const subscription = findZeebeSubscription(businessObject);

**Comment by barmac** [comment]
Actually, in v5.18.0 we upgraded `camunda-bpmn-js` from v3.8.0 to v3.10.2, and it contained an upgrade of `bpmn-js-element-templates` from v1.7.0 to v1.9.2.

**Comment by barmac** [comment]
This is the diff between these versions: https://github.com/bpmn-io/bpmn-js-element-templates/compare/v1.7.0...v1.9.2

**Comment by barmac** [comment]
I just noticed that in 5.18.0 the XML looks as expected when I create element from template via triple dot (create/append anything), but is wrong when template is applied to an existing element.

**Comment by barmac** [comment]
So this is a bug for sure. I will create an issue in the Modeler repo.

**Comment by barmac** [comment]
The Modeler issue: https://github.com/camunda/camunda-modeler/issues/4124

**Comment by barmac** [comment]
I am moving this to the backlog until the core issue is fixed. We will then add your template to the test suite.

**Comment by barmac** [comment]
This is fixed in https://github.com/bpmn-io/element-templates-cli/pull/17
